# Generated by Django 3.0.4 on 2020-05-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alllogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='alllogin',
            name='userid',
            field=models.IntegerField(default=10),
        ),
    ]
