# Generated by Django 3.0.4 on 2020-04-13 09:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_1', models.CharField(choices=[('I like Pizza', 'I like Pizza'), ('Hello World', 'Hello World'), ('What is coronavirus wwww.coronavirus.com', 'What is coronavirus wwww.coronavirus.com'), ('What is the meaning of life', 'What is the meaning of life')], default='I like Pizza', max_length=50)),
                ('PrivacyLoss', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
                ('burden', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
                ('benefit', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('I like Pizza', 'I like Pizza'), ('Hello World', 'Hello World'), ('What is coronavirus wwww.coronavirus.com', 'What is coronavirus wwww.coronavirus.com'), ('What is the meaning of life', 'What is the meaning of life')], default='I like Pizza', max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfriends', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=8), size=8)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfriends_req', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, unique=True), size=8), size=8)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
