# Generated by Django 3.0.4 on 2020-03-22 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1', models.CharField(max_length=50)),
                ('PS', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
                ('burden', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
                ('benefit', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_1', models.CharField(max_length=50)),
                ('PS', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
                ('burden', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
                ('benefit', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('I like Pizza', 'I like Pizza'), ('Hello World', 'Hello World'), ('What is coronavirus', 'What is coronavirus'), ('What is the meaning of life', 'What is the meaning of life')], default='I like Pizza', max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
