# Generated by Django 3.0.4 on 2020-10-04 17:43

from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('feedPosts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, unique=True), size=100), size=100)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('id_round', models.IntegerField(default=0)),
                ('code_operation', models.CharField(max_length=10)),
                ('post_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('burden', models.FloatField(default=0)),
                ('benefit', models.FloatField(default=0)),
                ('privacy_loss', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScorePerRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('id_round', models.IntegerField(default=0)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=100)),
                ('id_user', models.IntegerField(default=0, verbose_name=django.contrib.auth.models.User)),
                ('subCode', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='benefitRounds2',
            new_name='benefitRounds2',
        ),
        migrations.AddField(
            model_name='status',
            name='sumWithOutBenefit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='status',
            name='PrivacyLoss',
            field=models.CharField(choices=[('0.1$', '0.1$'), ('0.2$', '0.2$'), ('0.9$', '0.3$'), ('0.9$', '0.4$'), ('0.9$', '0.5$'), ('0.9$', '0.6$'), ('0.9$', '0.7$'), ('0.9$', '0.8$'), ('0.9$', '0.9$')], default='0$', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='benefit',
            field=models.CharField(choices=[('0.1$', '0.1$'), ('0.2$', '0.2$'), ('0.3$', '0.3$'), ('0.4$', '0.4$'), ('0.5$', '0.5$'), ('0.6$', '0.6$'), ('0.7$', '0.7$'), ('0.8$', '0.8$'), ('0.9$', '0.9$')], default='0$', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='burden',
            field=models.CharField(choices=[('0.1$', '0.1$'), ('0.2$', '0.2$'), ('0.3$', '0.3$'), ('0.4$', '0.4$'), ('0.5$', '0.5$'), ('0.6$', '0.6$'), ('0.7$', '0.7$'), ('0.8$', '0.8$'), ('0.9$', '0.9$')], default='0$', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('I like pizza', 'I like pizza'), ('What is the meaning of life', 'What is the meaning of life'), ('Im tired of the cornavirus ', 'Im tired of the cornavirus '), ('If there is no flour eat cakes', 'If there is no flour eat cakes'), ('Have a nice week', 'Have a nice week'), ('Im at the beach', 'Im at the beach'), ('Today, barbecue in the woods', 'Today, barbecue in the woods'), ('Please help us www.cancer.com/Xf58b22', 'Please help us www.cancer.com/Xf58b22'), ('In New York city', 'In New York city'), ('There was a crazy workout today', 'There was a crazy workout today'), ('Help us find Max www.myDog.com/Pi10g71', 'Help us find Max www.myDog.com/Pi10g71'), ('The best burger www.BK.com/Mn47l84', 'The best burger www.BK.com/Mn47l84'), ('NEWS www.Znet.com/Vj11w05', 'NEWS www.Znet.com/Vj11w05'), ('My cooking photo:)', 'My cooking photo:)'), ('Amazing song www.AC_DC.com/Yb12a24', 'Amazing song www.AC_DC.com/Yb12a24'), ('I bought an apartment in Tel Aviv', 'I bought an apartment in Tel Aviv'), ('Selling my guitar', 'Selling my guitar'), ('The food industry is destroying the world', 'The food industry is destroying the world'), ('Meat is murder www.vegetables.com/Vg99j47', 'Meat is murder www.vegetables.com/Vg99j47'), ('Here in Vegas', 'Here in Vegas'), ('I lost weight :)', 'I lost weight :)'), ('What is change ?!', 'What is change ?!'), ('Wanted waiter for www.MCdonalds.com/Kl46d12', 'Wanted waiter for www.MCdonalds.com/Kl46d12'), ('Happy birthday to Liel 25!', 'Happy birthday to Liel 25!'), ('Watching Game of Thrones tonight', 'Watching Game of Thrones tonight'), ('Save the date www.married1/1/20.com/Uw00u51', 'Save the date www.married1/1/20.com/Uw00u51'), ('Nail polish for $ 10', 'Nail polish for $ 10'), ('Look! a new haircut', 'Look! a new haircut'), ('funny vines www.youtube.com/Fu11y75', 'funny vines www.youtube.com/Fu11y75'), ('I hate emojis', 'I hate emojis')], default='I like Pizza', max_length=50),
        ),
        migrations.CreateModel(
            name='Ready',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='inEndScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
