# Generated by Django 3.0.4 on 2020-05-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='myfriends',
            field=models.CharField(default='dont', max_length=50),
        ),
    ]
