# Generated by Django 3.0.4 on 2020-03-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='option_1',
            new_name='comment_name',
        ),
    ]
