# Generated by Django 3.0.4 on 2020-10-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20201004_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScorePerRound',
        ),
    ]
