# Generated by Django 3.0.4 on 2020-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20200321_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(choices=[('Nice Post!', 'Nice Post!'), ('I am not agree with you!', 'I am not agree with you!'), ('Good opinion', 'Good opinion'), ('Cool sentences', 'Cool sentences')], default='Nice Post!', max_length=50)),
                ('PS', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
                ('burden', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
                ('benefit', models.CharField(choices=[('0$', '0$'), ('1$', '1$'), ('2$', '2$')], default='0$', max_length=50)),
            ],
        ),
    ]
