# Generated by Django 3.0.4 on 2020-05-08 07:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20200508_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='myfriends',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=8), size=8),
        ),
    ]
