# Generated by Django 3.0.4 on 2020-03-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_post_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post_Comments',
        ),
    ]
