# Generated by Django 3.0.4 on 2020-03-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20200320_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='year_in_school',
            new_name='status',
        ),
    ]
