# Generated by Django 3.0.4 on 2020-03-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='option_1',
        ),
    ]
