# Generated by Django 3.0.4 on 2020-03-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
