# Generated by Django 3.0.4 on 2020-03-28 08:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='myfriends',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=8), size=8),
        ),
    ]
