# Generated by Django 3.0.4 on 2020-03-28 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0008_auto_20200328_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Friends',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='userid',
            new_name='user',
        ),
    ]
