# Generated by Django 3.0.4 on 2020-03-28 10:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0010_auto_20200328_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='myfriends',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=8), size=8),
        ),
    ]
