# Generated by Django 3.0.4 on 2020-03-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0012_friend_requsts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend_requsts',
            old_name='myfriends_requests',
            new_name='myfriends_requsts',
        ),
    ]
