# Generated by Django 3.0.4 on 2020-08-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0015_auto_20200825_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='PrivacyLoss',
            field=models.CharField(choices=[('0.1$', '0.1$'), ('0.2$', '0.2$'), ('0.9$', '0.3$'), ('0.9$', '0.4$'), ('0.9$', '0.5$'), ('0.9$', '0.6$'), ('0.9$', '0.7$'), ('0.9$', '0.8$'), ('0.9$', '0.9$')], default='0$', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='benefit',
            field=models.CharField(choices=[('0.1$', '0.1$'), ('0.2$', '0.2$'), ('0.3$', '0.3$'), ('0.4$', '0.4$'), ('0.5$', '0.5$'), ('0.6$', '0.6$'), ('0.7$', '0.7$'), ('0.8$', '0.8$'), ('0.9$', '0.9$')], default='0$', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='burden',
            field=models.CharField(choices=[('0.1$', '0.1$'), ('0.2$', '0.2$'), ('0.3$', '0.3$'), ('0.4$', '0.4$'), ('0.5$', '0.5$'), ('0.6$', '0.6$'), ('0.7$', '0.7$'), ('0.8$', '0.8$'), ('0.9$', '0.9$')], default='0$', max_length=50),
        ),
    ]
