# Generated by Django 3.0.4 on 2020-03-29 09:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0017_auto_20200329_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='friend_requsts',
            new_name='Friend_req',
        ),
        migrations.RenameField(
            model_name='friend_req',
            old_name='myfriends_requsts',
            new_name='myfriends_req',
        ),
    ]
